### ISSUE TITLE
non primary foreign keys

### ISSUE THREAD

**Issue by joshraymo** [SoftwareBrothers/adminjs-prisma#17]
We were having issues with our foreignKey references when they were pointing to columns that were not primary keys.  This patch allowed us to use foreignKeys without them having to be primary keys.

This error was encountered in the following versions:
adminJS 5.11.0
@adminJs/Prisma 1.0.4

We were getting this error

```
Error: 
Invalid `this.manager.findMany()` invocation in
node_modules/@adminjs/prisma/lib/Resource.js:88:48

   85 const idProperty = this.properties().find((property) => property.isId());
   86 if (!idProperty)
   87     return [];
→  88 const results = yield this.manager.findMany({
        where: {
          id: {
            in: [
              'loremIpsum@gmail.com'
            ]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~
          }
        }
      })

Argument in: Got invalid value 
[
  'loremIpsum@gmail.com'
]
on prisma.findManyuser. Provided List<String>, expected List<Int>.
    at Document.validate (/node_modules/@prisma/client/runtime/index.js:47823:20)
    at PrismaClient._executeRequest (/node_modules/@prisma/client/runtime/index.js:49972:17)
    at consumer (/node_modules/@prisma/client/runtime/index.js:49916:23)
    at /node_modules/@prisma/client/runtime/index.js:49920:76
    at runInChildSpan (/node_modules/@prisma/client/runtime/index.js:49133:12)
    at /node_modules/@prisma/client/runtime/index.js:49920:20
    at AsyncResource.runInAsyncScope (node:async_hooks:199:9)
    at PrismaClient._request (/node_modules/@prisma/client/runtime/index.js:49919:86)
    at /node_modules/@prisma/client/runtime/index.js:46474:25
    at _callback (/node_modules/@prisma/client/runtime/index.js:46233:52)
```

The changes below were our solution

```diff
diff --git a/node_modules/@adminjs/prisma/lib/Resource.js b/node_modules/@adminjs/prisma/lib/Resource.js
index 4e7edb2..8c9e3da 100644
--- a/node_modules/@adminjs/prisma/lib/Resource.js
+++ b/node_modules/@adminjs/prisma/lib/Resource.js
@@ -80,14 +80,17 @@ class Resource extends adminjs_1.BaseResource {
             return new adminjs_1.BaseRecord(this.prepareReturnValues(result), this);
         });
     }
-    findMany(ids) {
+    findMany(ids, refPath = null) {
         return __awaiter(this, void 0, void 0, function* () {
-            const idProperty = this.properties().find((property) => property.isId());
+            const idProperty  = this.properties().find((property) => refPath ? refPath.propertyPath === property.propertyPath : property.isId())
+
             if (!idProperty)
                 return [];
             const results = yield this.manager.findMany({
                 where: {
-                    [idProperty.path()]: {
+                    [idProperty.propertyPath]: {
                         in: ids.map((id) => (0, converters_1.convertParam)(idProperty, this.model.fields, id)),
                     },
                 },
```

**Comment by emirhanyuce** [comment]
Hello do you have any updates or a work around on this issue? I am having a similar issue with two resources I have where they reference a non primary foreign key, the resulting prisma query generated by the adminjs adapter to list the records under these resources is wrong hence breaking the adminjs pages related to these resources.

**Comment by emirhanyuce** [comment]
Hello, we are also facing a similar issue where we have some resources referencing some non primary foreign keys, which broke the corresponding resource pages, your solution seems to fix our issue as well thanks for the solution, I still don't know how might we apply this to a dockerized solution.

**Comment by duncan-oxd** [comment]
Experiencing this with Sequelize models in AdminJS 7 as well. Good to know it's not specific to the ORM, at least.
