### ISSUE TITLE
There are no adapters supporting one of the resource you provided

### ISSUE THREAD

**Issue by darr1s** [SoftwareBrothers/adminjs-prisma#47]
## Background
I am trying to setup AdminJS in my stack. I am using Nest.js.

## Version
```
    "@adminjs/express": "^6.0.1",
    "@adminjs/nestjs": "^6.0.1",
    "@adminjs/prisma": "^5.0.1",
    "@nestjs/platform-express": "^10.2.6",
    "adminjs": "^7.2.2",
    "prisma": "^5.3.1",
```

## Setup
```
import { Module } from '@nestjs/common';
import { ModuleRef } from '@nestjs/core';

import { Prisma } from '@prisma/client';
import { DMMFClass } from '@prisma/client/runtime/library';

import { PrismaService } from 'src/database/prisma.service';

@Module({
  imports: [
    Promise.all([
      import('@adminjs/nestjs'),
      import('@adminjs/express'),
      import('@adminjs/prisma'),
      import('adminjs'),
    ]).then(
      ([
        { AdminModule },
        { default: AdminJSExpress },
        { getModelByName, Database, Resource },
        { default: AdminJS },
      ]) => {
        AdminJS.registerAdapter({ Database, Resource });
        AdminModule.createAdmin;

        return AdminModule.createAdminAsync({
          imports: [
          ],
          inject: [
            PrismaService,
            ModuleRef,
          ],
          useFactory: (
            prisma: PrismaService,
            _,
          ) => {
            const dmmf = (prisma as any)._baseDmmf as DMMFClass;
            type CreateAdminAsync = typeof AdminModule.createAdmin;
            type Options = Parameters<CreateAdminAsync>[0];
            type AdminJSOptions = Pick<Options, 'adminJsOptions'>;

            const options: AdminJSOptions = {
              adminJsOptions: {
                rootPath: '/admin',
                branding: {
                  companyName: 'Development Admin Panel',
                  logo: '',
                },
                resources: [
                  {
                    resource: {
                      model: getModelByName('User', {
                        Prisma: { dmmf: Prisma.dmmf },
                      }),
                      client: prisma,
                      module: { Prisma: { dmmf: Prisma.dmmf } },
                    },
                    options: {},
                  },
                ],
              },
            };

            // (options as any).customLoader = AdminJSExpress;

            return options;
          },
        });
      },
    ),
  ],
})
export class AdminModule {}
```

## Error
```
(node:394465) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:394465) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
NoResourceAdapterError: There are no adapters supporting one of the resource you provided
    at file:///home/darris/org/myapp/api/node_modules/.pnpm/adminjs@7.2.2/node_modules/adminjs/lib/backend/utils/resources-factory/resources-factory.js:73:15
    at Array.map (<anonymous>)
    at ResourcesFactory._convertResources (file:///home/darris/org/myapp/api/node_modules/.pnpm/adminjs@7.2.2/node_modules/adminjs/lib/backend/utils/resources-factory/resources-factory.js:68:22)
    at ResourcesFactory.buildResources (file:///home/darris/org/myapp/api/node_modules/.pnpm/adminjs@7.2.2/node_modules/adminjs/lib/backend/utils/resources-factory/resources-factory.js:28:35)
    at new AdminJS (file:///home/darris/org/myapp/api/node_modules/.pnpm/adminjs@7.2.2/node_modules/adminjs/lib/adminjs.js:80:39)
    at AdminModule.onModuleInit (file:///home/darris/org/myapp/api/node_modules/.pnpm/@adminjs+nestjs@6.0.1_@nestjs+common@10.2.6_@nestjs+core@10.2.6_adminjs@7.2.2_rxjs@7.8.1/node_modules/@adminjs/nestjs/build/admin.module.js:70:23)
    at callModuleInitHook (/home/darris/org/myapp/api/node_modules/.pnpm/@nestjs+core@10.2.6_@nestjs+common@10.2.6_@nestjs+platform-express@10.2.6_reflect-metadata@0.1.13_rxjs@7.8.1/node_modules/@nestjs/core/hooks/on-module-init.hook.js:51:35)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at NestApplication.callInitHook (/home/darris/org/myapp/api/node_modules/.pnpm/@nestjs+core@10.2.6_@nestjs+common@10.2.6_@nestjs+platform-express@10.2.6_reflect-metadata@0.1.13_rxjs@7.8.1/node_modules/@nestjs/core/nest-application-context.js:223:13)
    at NestApplication.init (/home/darris/org/myapp/api/node_modules/.pnpm/@nestjs+core@10.2.6_@nestjs+common@10.2.6_@nestjs+platform-express@10.2.6_reflect-metadata@0.1.13_rxjs@7.8.1/node_modules/@nestjs/core/nest-application.js:100:9)
```

**Comment by darr1s** [comment]
Closed, just noticed is my PrismaService have other public method that exposes the client.
